// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';

export function SaveToken(arg1:string):Promise<void>;

export function Session():Promise<session.Session>;
