// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveToken(arg1) {
  return window['go']['main']['App']['SaveToken'](arg1);
}

export function Session() {
  return window['go']['main']['App']['Session']();
}
